---

# Setup database tier
# - name: setup database tier
#   become: yes
#   hosts: appdbs
#   roles:
#     - db-tier

# # Setup application servers tier
# - name: setup app tier
#   hosts: apps
#   become: yes
#   gather_facts: true
#   roles:
#     - base-config
#     - app-tier

# Setup load balancer tier
- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - lb-tier

